feat: Introduce phone apis (#4)
* Simple get phones

* Phone initial

* Avoid x-powered-by

* Enable 4 week caching

* Exception: Router

* Ran xo

* Include mocha and tests

* v1 phones

* XO formatting

* Test phone

* Ensure no onlys in the tests

* Check result

* Use exit code in one line

* Negate the condition

* Mocha unit tests

* Use mocha-junit-reporter

* Use env args

* Debug

* Debug more

* Don't use tilde

* Use npm directly

* go back to install

* Use code coverage

* Now that lock is there, ci can be used

* Use mocha dir

* Add morgan logging

* Rename to default

* xo

* Do xo stuff separately

* Fix format

* Verify ETag

* Return 304 blindly whenever an ETag is sent

* Use if-else

* Install faster

* Error handling

* Not only

* Use node 14

* Node 14.16

* Attempt to use nodeVersion param

* Support NODE_VERSION in the arg

* Prettier

* Pipeline nodeVersion

* Ignore unused here

* Error handler

* Renamed to fix xo

* XO fix

* Fixed imports

* Use manufacturer/model

* Don't do next

* xo fixes

* Only do release on master

* Hard-coded for testing

* Use asyncHandler

* Support reading from file

* Verify all pixel 5 stuff

* Support PUT

* XO fixes

* mkdir data

* Test ram

* Add some additonal gsmArena info

* Make data dir

* Mandatory parameters

* Improve tests

* Keep single object for phone

* Start documenting

* Completed GET

* Finished get docs

* Document everything

* Update README

* doc api-docs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,16 +4,43 @@ orbs:
   node: circleci/node@4
   docker: circleci/docker@1
 
+parameters:
+  nodeVersion:
+    description: The version of node to build.
+    type: string
+    default: '14.16'
+
 jobs:
   test:
     executor: 
       name: node/default
+      tag: << pipeline.parameters.nodeVersion >>
     steps:
       - checkout
-      - node/install-packages:
-          override-ci-command: npm install
+      - node/install-packages
       - run:
-          command: npm test
+          command: |
+            export DATA_DIR=$(mktemp -d)
+            npm test
+          environment:
+            MOCHA_FILE: ./mocha/test-results.xml
+            MOCHA_REPORTER_ARGS: --reporter mocha-junit-reporter
+      - store_test_results:
+          path: ./mocha
+      - store_artifacts:
+          path: ./mocha/test-results.xml
+      - store_artifacts:
+          path: ./coverage/
+      - run:
+          name: Verify XO
+          command: npm run xo-verify
+      - run:
+          name: Ensure only not used
+          command: |
+            if grep ".only" -Rq test/; then
+              echo "Tests include only; failng"
+              exit 1
+            fi
   docker:
     machine: 
       image: ubuntu-2004:202101-01
@@ -40,6 +67,7 @@ jobs:
           image: ${CIRCLE_PROJECT_REPONAME}
           registry: ${DOCKER_REGISTRY}
           tag: ${DOCKER_TAG},${ALTERNATE_TAG}
+          extra_build_args: --build-arg NODE_VERSION=<< pipeline.parameters.nodeVersion >>
       - docker/push:
           image: ${CIRCLE_PROJECT_REPONAME}
           registry: ${DOCKER_REGISTRY}
@@ -54,7 +82,7 @@ jobs:
         default: false
     steps:
       - checkout
-      - run: npm install
+      - run: npm ci
       - run: npm install -D @semantic-release/exec
       - attach_workspace:
           at: /tmp/workspace
@@ -80,7 +108,7 @@ jobs:
             - version.txt
 
 workflows:
-  build-deploy:
+  default:
     jobs:
       - release:
           name: pre-release
@@ -92,9 +120,9 @@ workflows:
             - pre-release
       - release:
           prerelease: false
-#          filters:
-#            branches:
-#              only:
-#                - main
           requires:
             - docker
+          filters:
+            branches:
+              only:
+                - main
